export const GET_CONTACTS = 'GET_CONTACTS'
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS'
export const GET_CONTACTS_FAILURE = 'GET_CONTACTS_FAILURE'

export const POST_CONTACT = 'POST_CONTACT'
export const POST_CONTACT_SUCCESS = 'POST_CONTACT_SUCCESS'
export const POST_CONTACT_FAILURE = 'POST_CONTACT_FAILURE'

export const DELETE_CONTACT = 'DELETE_CONTACT'
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS'
export const DELETE_CONTACT_FAILURE = 'DELETE_CONTACT_FAILURE'
